### ISSUE TITLE
[.NET 8.0] Breakpoints not hit

### ISSUE THREAD

**Issue by fsdenrico** [FlorianRappl/Piral.Blazor#142] opened 2024-04-08 11:41 UTC
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Shell:

blazor v8.0.13
piral v1.5.2
piral-blazor v1.5.2

dotnet sdk:

v8.0.203

## Description

- Breakpoints not hit

## Steps to Reproduce

- set v8.0.13 instead of v8.0.14 in Shell and Pilet (example currently not working)
- run `run.ps1`
- set `Pilet` as startup project
- start with debugger attached
- set breakpoint at `CounterPage.IncrementCount()`

## Expected behavior

- breakpoint hit

## Actual behavior

- breakpoint not hit

## Possible Origin / Solution

- blazor-7.0 branch works as expected

**Comment by FlorianRappl** [comment] 2024-04-08 12:04
I think this also works with .NET 8 (try the latest version; 8.0.14-pre.20240404.1).

**Comment by fsdenrico** [comment] 2024-04-08 12:48
I already tried the newest pre version but it did not make any difference.

**Comment by FlorianRappl** [comment] 2024-04-08 15:04
Are you using a portable pdb? Because this was reported in the community chat like a week ago and I'm the end the issue was on the user side - pdb set to full instead of portable.

**Comment by fsdenrico** [comment] 2024-04-09 08:21
As far as I see you set the type of pdb in the csproj file. I am just using your example project with modified versions since the example is currently not running. So pdb should be set to portable as it is the default value.

**Comment by FlorianRappl** [comment] 2024-04-09 08:34
Well, it's working for me (and others, as reported in community chat). So I think I'll close this one unless we hear back with a clear reproducible.

**Comment by xigoku** [comment] 2024-04-09 13:25
Issue with v8.0.13
![Pilet 8 0 13](https://github.com/smapiot/Piral.Blazor/assets/34597495/e0c7a576-c7ee-459f-bfc2-8d2a2797909a)
Issue with v8.0.14pre
![Pilet 8 0 14pre](https://github.com/smapiot/Piral.Blazor/assets/34597495/8220bd4e-4f2f-44a1-aa03-386807f6d000)

**Comment by fsdschmidt** [comment] 2024-04-09 14:10
Now we analyzed Chrome DevTools Protocol and observed that Chrome gets breakpoints from Rider or Visual Studio (also Rider marks the breakpoint as active with the little check). In the following little video you could see that Chrome protocol monitor does not records any messages without breakpoint and records Debugger messages with breakpoint. But unfortunately the breakpoint pauses and immediately resumes and we have no idea why this resume happens. 

Please help, net8 debugging is impossible across our whole team and we also reproduced it with piral example solution. Debugging inside new project from microsoft wasm template works. 

https://github.com/smapiot/Piral.Blazor/assets/43231196/2f89b1cb-ee46-4a58-aebb-2786de310a75

**Comment by FlorianRappl** [comment] 2024-04-11 14:42
Good news - I can reproduce it and I also found out what the reason for this behavior is. A fix is incoming and should be out with the next pre-release (currently in build). Once the fix is working I'll publish the 8.0.14.

**Comment by FlorianRappl** [comment] 2024-04-11 15:28
Working for me - please also try: 8.0.14-pre.20240411.3

Once you confirm its working we can release 8.0.14.

**Comment by fsdschmidt** [comment] 2024-04-12 06:27
Thanks for your fix! I tried it inside example project and are happy to cofirm that breakpoint inside `CounterPage.IncrementCount()` works again. Unfortunately breakpoints inside dependent solution projects (DesignSystem) still not work. But I think this is another problem, because I see Pilet.pdb loaded in browser but no DesignSystem.pdb:

![Bildschirmfoto 2024-04-12 um 08 20 17](https://github.com/smapiot/Piral.Blazor/assets/43231196/260d4dbd-47da-499b-9e0f-737c84ca3ffc)

This are my local changes, I added a call to ConsoleMessageService and the breakpoint inside `ConsoleMessageService.LogMessageToConsole()` won't hit:

```
diff --git a/example/app-shell/package.json b/example/app-shell/package.json
index 9a02739..0f58b81 100644
--- a/example/app-shell/package.json
+++ b/example/app-shell/package.json
@@ -22,7 +22,7 @@
     "postUpgrade": ""
   },
   "dependencies": {
-    "blazor": "8.0.14",
+    "blazor": "8.0.14-pre.20240411.3",
     "piral": "1.5.2",
     "piral-blazor": "1.5.2"
   },
diff --git a/example/pilet/Pilet/Components/CounterPage.razor b/example/pilet/Pilet/Components/CounterPage.razor
index ca9b348..27b0dd7 100644
--- a/example/pilet/Pilet/Components/CounterPage.razor
+++ b/example/pilet/Pilet/Components/CounterPage.razor
@@ -25,5 +25,6 @@
     void IncrementCount()
     {
         currentCount++;
+        consoleMessageService.LogMessageToConsole("increment");
     }
 }
diff --git a/example/pilet/Pilet/Pilet.csproj b/example/pilet/Pilet/Pilet.csproj
index c11d148..f8859e4 100644
--- a/example/pilet/Pilet/Pilet.csproj
+++ b/example/pilet/Pilet/Pilet.csproj
@@ -8,9 +8,9 @@
   <ItemGroup>
     <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.4" />
     <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.0" PrivateAssets="all" />
-    <PackageReference Include="Piral.Blazor.DevServer" Version="8.0.14" />
-    <PackageReference Include="Piral.Blazor.Utils" Version="8.0.14" />
-    <PackageReference Include="Piral.Blazor.Tools" Version="8.0.14" />
+    <PackageReference Include="Piral.Blazor.DevServer" Version="8.0.14-pre.20240411.3" />
+    <PackageReference Include="Piral.Blazor.Utils" Version="8.0.14-pre.20240411.3" />
+    <PackageReference Include="Piral.Blazor.Tools" Version="8.0.14-pre.20240411.3" />
   </ItemGroup>

   <ItemGroup>
```

**Comment by FlorianRappl** [comment] 2024-04-12 07:36
OK I am not sure if the problem with DesignSystem.pdb is constraint to .NET 8 or what the implications are.

For now I close the bug (as essentially debugging itself is working on .NET 8 - its just a matter / issue if the pdb is not there). For the follow up issue we create a new bug and solve it with v15.

**Closed as completed by FlorianRappl** 2024-04-12 07:36 UTC
Labels: bug, blazor-v8

**Comment by fsdschmidt** [comment] 2024-04-12 08:03
Ok I'm fine with follow up. But in my opinion it is .NET8 issue, because I just startet identical setup with .NET7 branch and `ConsoleMessageService.LogMessageToConsole()` breakpoint hits. But for .NET7 DesignSystem.pdb is loaded in browser.

Our pilets follow a layered project structure, so the pilet project is just the UI head. The interesting code for debugging is located in business logic and data access projects (like DesignSystem in example). Because of this solution structure, debugging pilet dependencies inside solution is crucial for us.

**Comment by fsdenrico** [comment] 2024-04-12 09:47
Debugging in `Pilet.csproj` works with v8.0.14 and VS 2022 for me, too. Debugging in `MyButton.razor` is still not possible. Bug can be closed.
